version: '3'
services:
  db:
    container_name: postgres_database
    image: postgres:15.1
    restart: always
    volumes:
      - ./tools/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=testdb
  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./tools/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456 
      - PGADMIN_DEFAULT_EMAIL=superman@google.com